[Vidéo 10](https://www.youtube.com/watch?v=Wibxjrxf5ko&list=PLeo1K3hjS3uu7CxAacxVndI4bE_o3BDtO&index=10)

In [1]:
import numpy as np

In [2]:
revenue = np.array([
    [180, 200, 220],
    [24, 36, 40],
    [12, 18, 20]
])

expenses = np.array([
    [80, 90, 100],
    [10, 16, 20],
    [8, 10, 10]
])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([
    [30, 40, 50],
    [5, 10, 15],
    [2, 5, 7]
])

In [7]:
price_per_unit * units # Ce n'est pas comme cela qu'on multiplie des matrices
# Numpy broadcasting : si les deux matrices multiplier, n'ont pas la même forme,
# numpy copie-colle des valeurs pour qu'elles soient de même taille

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [10]:
np.dot(price_per_unit, units) # multiplication de matrices
# ATTENTION : l'ordre des matrice dans la fonction à de l'importance. La multiplication
# de matrice n'est pas commutative

array([34400, 50000, 64400])