In [17]:
import numpy as np

y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

## Mean Absolute Error function
---

In [18]:
def mae(y_true, y_predicted):
  total_error = 0
  for yt, yp in zip(y_true, y_predicted):
    total_error += abs(yt - yp)
  print("Total error :", total_error)

  mae = total_error / len(y_true)
  print("MAE :", mae)
  return mae

In [19]:
mae(y_true, y_predicted)

Total error : 2.5
MAE : 0.5


0.5

In [20]:
# MAE only using numpy
np.mean(np.abs(y_predicted - y_true))

0.5

## Log Loss function
---

In [26]:
np.log([0])

<ipython-input-26-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [27]:
np.log([1])

array([0.])

In [24]:
np.log([0.000000000000000001])

array([-41.44653167])

In [25]:
epsilon = 1e-15 # nombre très proche de 0 parceque log(0) n'est pas possible

In [38]:
y_predicted_new = [max(i, epsilon) for i in y_predicted] # replace 0
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new] # replace 1
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [39]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
np.log(y_predicted) # pas utilisable ...

<ipython-input-40-bdbdba006d24>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted) # pas utilisable ...


array([  0.,   0., -inf, -inf,   0.])

In [41]:
# Log Loss function :
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [45]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i, epsilon) for i in y_predicted] # replace 0
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new] # replace 1
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [46]:
log_loss(y_true=y_true, y_predicted=y_predicted)

17.2696280766844

## Mean Square Error function
---

In [47]:
def mse(y_true, y_predicted):
  total_error = 0
  for yt, yp in zip(y_true, y_predicted):
    total_error += abs(yt - yp) ** 2
  print("Total squared error :", total_error)

  mse = total_error / len(y_true)
  print("MSE :", mse)
  return mse

In [48]:
mse(y_true, y_predicted)

Total squared error : 1.83
MSE : 0.366


0.366

In [50]:
# np.mean(np.abs(y_predicted - y_true) ** 2)
np.mean(np.square(y_predicted - y_true))

0.366