In [15]:
import numpy as np

In [16]:
tab1 = np.array([1, 2, 3, 4, 5])
tab1

array([1, 2, 3, 4, 5])

In [22]:
tab2 = np.array([6, 7, 8, 9, 10])
tab2

array([ 6,  7,  8,  9, 10])

In [18]:
5 * tab1

array([ 5, 10, 15, 20, 25])

In [19]:
5 * tab1 + 2

array([ 7, 12, 17, 22, 27])

In [20]:
2 * tab2

array([12, 14, 16, 18])

In [23]:
5 * tab1 + 2 * tab2

array([17, 24, 31, 38, 45])